<h3>Sorting out MP3 playback</h3>
<p>Like with any other Linux based opperating system, MeeGo works with OGG format files out of the box, however it does require some additional codecs to play MP3 format files. I did a bit of research into the best (and most compatable) one to use, and came to the conclusion that <a href="#">fluendo</a> seems to be the best to use. You can download the latest version of these codecs by <a href="#">signing up with fluendo</a> or you can <a href="#">quick-download the version I'm using</a>. Installing is very simple, simply double click on the .rpm file and "okay" the popup to install. Or for those of you wanting to dabble in terminal, navigate to the location you Downloaded the file and simply run:<quote>######</quote></p>

<h3>How to extract .rar archives</h3>
<p>Although right-clicking on a file with .rar extension will show the "extract here" option, again the necessary codec to perform this action will be missing, and so far I've had no luck with the built-in search for codecs. After a bit of research I managed to find <a href="#">an rpm installer for unrar on MeeGo</a>. To run it simply double click on the file or navigate to the file and run the following command in terminal:<quote>######</quote></p>

<h3>Adding additional social feeds to "status" and "myzone"</h3>
<p>By default the only services you will see in MeeGo 1.2 are facebook, and something called #######. There is however capabilities to support far more than just these two, the only thing missing is the API key authorisation. Adding the API keys requires simply putting a file with the name of the service and the contents as the key into the right folder. I have put together a zipped up folder of <a href="#">all the extra services I know of</a>, but you can always add other supported ones in the same way. To install simply extract the file from the archive and copy then (with administrative permissions) into /####/####/####/####.</p>

<h3>Fullscreen flash</h3>
<p>This may only be my machine, but I've had issues with watching flash videos (such as youtube) in full screen. The screen freezes and, although I can still hear the sound, there seems to be no way to get out of it. At the time of writing I have no work-around for this, other than don't put flash videos into full screen. It doesn't happen all the time, but when it does it's annoying having to reboot (though the blow is lessened by the fast reboot speed of MeeGo).</p>
